source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GFPlayerView_Example', :exclusive => true do
  pod "GFPlayerView", :path => "../"
end

target 'GFPlayerView_Tests', :exclusive => true do
  pod "GFPlayerView", :path => "../"

  
end
